spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: lb://user-service # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/api/mall/user/**, /admin/login/**, /admin/logout/**, /admin/user/**
        - id: collections_service
          uri: lb://collections-service # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/api/mall/order/getFavList, /api/mall/order/addToFav, /api/mall/order/deleteItemFromFav
        - id: cart_service
          uri: lb://cart-service # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/api/mall/order/addToCart, /api/mall/order/getCartList, /api/mall/order/deleteItemsFromCart, /api/mall/order/changeItemNumInCart, /api/mall/order/settleAccounts
        - id: orders_service
          uri: lb://orders-service # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/api/mall/order/**, /admin/orderHistoryAll/**, /admin/orderNowAll/**, /admin/orderHistorySearch/**, /admin/orderNowSearch/**, /admin/updateOrder, /admin/deleteOrder
        - id: product_service
          uri: lb://product-service # lb协议表示启用负载均衡功能，然后后面跟着微服务名称
          predicates:
            - Path=/api/mall/goods/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:8081"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000

# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

#配置服务器tomcat的参数配置
server:
  port: 8085
  servlet:
    context-path: /
