---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql5
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: mysql5
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql5
    spec:
      containers:
        - name: mysql5
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:mysql5
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:eureka-server
          imagePullPolicy: Always
          ports:
            - containerPort: 8761

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8085

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:user-service
          imagePullPolicy: Always
          env:
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"
            - name: DB_URL
              value: "mysql5:3306/lab2"
          ports:
            - containerPort: 8090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:orders-service
          imagePullPolicy: Always
          env:
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"
            - name: DB_URL
              value: "mysql5:3306/lab2"
          ports:
            - containerPort: 8095

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:product-service
          imagePullPolicy: Always
          env:
            - name: USERNAME
              value: "root"
            - name: PASSWORD
              value: "123456"
            - name: DB_URL
              value: "mysql5:3306/lab2"
          ports:
            - containerPort: 8100

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinemart-vue
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: onlinemart-vue
  template:
    metadata:
      labels:
        app: onlinemart-vue
    spec:
      containers:
        - name: onlinemart-vue
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:onlinemart-vue
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinemart-backstage
  namespace: ase-ns-08
spec:
  selector:
    matchLabels:
      app: onlinemart-backstage
  template:
    metadata:
      labels:
        app: onlinemart-backstage
    spec:
      containers:
        - name: onlinemart-backstage
          image: registry.cn-shanghai.aliyuncs.com/fdu_adv_soft/k8s_08:onlinemart-backstage
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: mysql5
  namespace: ase-ns-08
spec:
  ports:
    - port: 3306
  selector:
    app: mysql5

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: ase-ns-08
spec:
  ports:
    - port: 8761
  selector:
    app: eureka-server

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ase-ns-08
spec:
  ports:
    - port: 8085
  selector:
    app: gateway

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ase-ns-08
spec:
  ports:
    - port: 8090
  selector:
    app: user-service

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: ase-ns-08
spec:
  ports:
    - port: 8095
  selector:
    app: orders-service

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ase-ns-08
spec:
  ports:
    - port: 8100
  selector:
    app: product-service

---
apiVersion: v1
kind: Service
metadata:
  name: onlinemart-vue
  namespace: ase-ns-08
spec:
  type: LoadBalancer
  selector:
    app: onlinemart-vue
  ports:
    - protocol: TCP
      port: 1024
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: onlinemart-backstage
  namespace: ase-ns-08
spec:
  type: LoadBalancer
  selector:
    app: onlinemart-backstage
  ports:
    - protocol: TCP
      port: 1024
      targetPort: 8081