apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: onlinemart-backstage
  name: onlinemart-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onlinemart-backstage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: onlinemart-backstage
    spec:
      containers:
        - image: peichengxuan/onlinemart-backstage
          name: onlinemart-backstage
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
