apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orders-service
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mynetwork: "true"
        io.kompose.service: orders-service
    spec:
      containers:
        - image: peichengxuan/orders-service
          name: orders-service
          ports:
            - containerPort: 8095
          resources: {}
      restartPolicy: Always
status: {}
